// Generated by `wit-bindgen` 0.19.2. DO NOT EDIT!
#include "ml.h"


__attribute__((__import_module__("wasi:nn/tensor"), __import_name__("[constructor]tensor")))
extern int32_t __wasm_import_wasi_nn_tensor_constructor_tensor(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:nn/tensor"), __import_name__("[method]tensor.dimensions")))
extern void __wasm_import_wasi_nn_tensor_method_tensor_dimensions(int32_t, int32_t);

__attribute__((__import_module__("wasi:nn/tensor"), __import_name__("[method]tensor.ty")))
extern int32_t __wasm_import_wasi_nn_tensor_method_tensor_ty(int32_t);

__attribute__((__import_module__("wasi:nn/tensor"), __import_name__("[method]tensor.data")))
extern void __wasm_import_wasi_nn_tensor_method_tensor_data(int32_t, int32_t);

__attribute__((__import_module__("wasi:nn/errors"), __import_name__("[constructor]error")))
extern int32_t __wasm_import_wasi_nn_errors_constructor_error(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:nn/errors"), __import_name__("[method]error.code")))
extern int32_t __wasm_import_wasi_nn_errors_method_error_code(int32_t);

__attribute__((__import_module__("wasi:nn/errors"), __import_name__("[method]error.data")))
extern void __wasm_import_wasi_nn_errors_method_error_data(int32_t, int32_t);

__attribute__((__import_module__("wasi:nn/inference"), __import_name__("[method]graph-execution-context.set-input")))
extern void __wasm_import_wasi_nn_inference_method_graph_execution_context_set_input(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:nn/inference"), __import_name__("[method]graph-execution-context.compute")))
extern void __wasm_import_wasi_nn_inference_method_graph_execution_context_compute(int32_t, int32_t);

__attribute__((__import_module__("wasi:nn/inference"), __import_name__("[method]graph-execution-context.get-output")))
extern void __wasm_import_wasi_nn_inference_method_graph_execution_context_get_output(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:nn/graph"), __import_name__("[method]graph.init-execution-context")))
extern void __wasm_import_wasi_nn_graph_method_graph_init_execution_context(int32_t, int32_t);

__attribute__((__import_module__("wasi:nn/graph"), __import_name__("load")))
extern void __wasm_import_wasi_nn_graph_load(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:nn/graph"), __import_name__("load-by-name")))
extern void __wasm_import_wasi_nn_graph_load_by_name(int32_t, int32_t, int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void wasi_nn_tensor_tensor_dimensions_free(wasi_nn_tensor_tensor_dimensions_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void wasi_nn_tensor_tensor_data_free(wasi_nn_tensor_tensor_data_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

__attribute__((__import_module__("wasi:nn/tensor"), __import_name__("[resource-drop]tensor")))
extern void __wasm_import_wasi_nn_tensor_tensor_drop(int32_t handle);

void wasi_nn_tensor_tensor_drop_own(wasi_nn_tensor_own_tensor_t handle) {
  __wasm_import_wasi_nn_tensor_tensor_drop(handle.__handle);
}

wasi_nn_tensor_borrow_tensor_t wasi_nn_tensor_borrow_tensor(wasi_nn_tensor_own_tensor_t arg) {
  return (wasi_nn_tensor_borrow_tensor_t) { arg.__handle };
}

__attribute__((__import_module__("wasi:nn/errors"), __import_name__("[resource-drop]error")))
extern void __wasm_import_wasi_nn_errors_error_drop(int32_t handle);

void wasi_nn_errors_error_drop_own(wasi_nn_errors_own_error_t handle) {
  __wasm_import_wasi_nn_errors_error_drop(handle.__handle);
}

wasi_nn_errors_borrow_error_t wasi_nn_errors_borrow_error(wasi_nn_errors_own_error_t arg) {
  return (wasi_nn_errors_borrow_error_t) { arg.__handle };
}

void wasi_nn_inference_tensor_data_free(wasi_nn_inference_tensor_data_t *ptr) {
  wasi_nn_tensor_tensor_data_free(ptr);
}

__attribute__((__import_module__("wasi:nn/inference"), __import_name__("[resource-drop]graph-execution-context")))
extern void __wasm_import_wasi_nn_inference_graph_execution_context_drop(int32_t handle);

void wasi_nn_inference_graph_execution_context_drop_own(wasi_nn_inference_own_graph_execution_context_t handle) {
  __wasm_import_wasi_nn_inference_graph_execution_context_drop(handle.__handle);
}

wasi_nn_inference_borrow_graph_execution_context_t wasi_nn_inference_borrow_graph_execution_context(wasi_nn_inference_own_graph_execution_context_t arg) {
  return (wasi_nn_inference_borrow_graph_execution_context_t) { arg.__handle };
}

void wasi_nn_inference_result_void_own_error_free(wasi_nn_inference_result_void_own_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void wasi_nn_inference_result_own_tensor_own_error_free(wasi_nn_inference_result_own_tensor_own_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

__attribute__((__import_module__("wasi:nn/graph"), __import_name__("[resource-drop]graph")))
extern void __wasm_import_wasi_nn_graph_graph_drop(int32_t handle);

void wasi_nn_graph_graph_drop_own(wasi_nn_graph_own_graph_t handle) {
  __wasm_import_wasi_nn_graph_graph_drop(handle.__handle);
}

wasi_nn_graph_borrow_graph_t wasi_nn_graph_borrow_graph(wasi_nn_graph_own_graph_t arg) {
  return (wasi_nn_graph_borrow_graph_t) { arg.__handle };
}

void wasi_nn_graph_graph_builder_free(wasi_nn_graph_graph_builder_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void wasi_nn_graph_result_own_graph_execution_context_own_error_free(wasi_nn_graph_result_own_graph_execution_context_own_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void ml_list_graph_builder_free(ml_list_graph_builder_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    wasi_nn_graph_graph_builder_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void wasi_nn_graph_result_own_graph_own_error_free(wasi_nn_graph_result_own_graph_own_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void ml_string_set(ml_string_t *ret, char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void ml_string_dup(ml_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void ml_string_free(ml_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

wasi_nn_tensor_own_tensor_t wasi_nn_tensor_constructor_tensor(wasi_nn_tensor_tensor_dimensions_t *dimensions, wasi_nn_tensor_tensor_type_t ty, wasi_nn_tensor_tensor_data_t *data) {
  int32_t ret = __wasm_import_wasi_nn_tensor_constructor_tensor((int32_t) (*dimensions).ptr, (int32_t) (*dimensions).len, (int32_t) ty, (int32_t) (*data).ptr, (int32_t) (*data).len);
  return (wasi_nn_tensor_own_tensor_t) { ret };
}

void wasi_nn_tensor_method_tensor_dimensions(wasi_nn_tensor_borrow_tensor_t self, wasi_nn_tensor_tensor_dimensions_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_nn_tensor_method_tensor_dimensions((self).__handle, ptr);
  *ret = (wasi_nn_tensor_tensor_dimensions_t) { (uint32_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

wasi_nn_tensor_tensor_type_t wasi_nn_tensor_method_tensor_ty(wasi_nn_tensor_borrow_tensor_t self) {
  int32_t ret = __wasm_import_wasi_nn_tensor_method_tensor_ty((self).__handle);
  return ret;
}

void wasi_nn_tensor_method_tensor_data(wasi_nn_tensor_borrow_tensor_t self, wasi_nn_tensor_tensor_data_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_nn_tensor_method_tensor_data((self).__handle, ptr);
  *ret = (wasi_nn_tensor_tensor_data_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

wasi_nn_errors_own_error_t wasi_nn_errors_constructor_error(wasi_nn_errors_error_code_t code, ml_string_t *data) {
  int32_t ret = __wasm_import_wasi_nn_errors_constructor_error((int32_t) code, (int32_t) (*data).ptr, (int32_t) (*data).len);
  return (wasi_nn_errors_own_error_t) { ret };
}

wasi_nn_errors_error_code_t wasi_nn_errors_method_error_code(wasi_nn_errors_borrow_error_t self) {
  int32_t ret = __wasm_import_wasi_nn_errors_method_error_code((self).__handle);
  return ret;
}

void wasi_nn_errors_method_error_data(wasi_nn_errors_borrow_error_t self, ml_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_nn_errors_method_error_data((self).__handle, ptr);
  *ret = (ml_string_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wasi_nn_inference_method_graph_execution_context_set_input(wasi_nn_inference_borrow_graph_execution_context_t self, ml_string_t *name, wasi_nn_inference_own_tensor_t tensor, wasi_nn_inference_result_void_own_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_nn_inference_method_graph_execution_context_set_input((self).__handle, (int32_t) (*name).ptr, (int32_t) (*name).len, (tensor).__handle, ptr);
  wasi_nn_inference_result_void_own_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (wasi_nn_inference_own_error_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
  }
  *ret = result;
}

void wasi_nn_inference_method_graph_execution_context_compute(wasi_nn_inference_borrow_graph_execution_context_t self, wasi_nn_inference_result_void_own_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_nn_inference_method_graph_execution_context_compute((self).__handle, ptr);
  wasi_nn_inference_result_void_own_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (wasi_nn_inference_own_error_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
  }
  *ret = result;
}

void wasi_nn_inference_method_graph_execution_context_get_output(wasi_nn_inference_borrow_graph_execution_context_t self, ml_string_t *name, wasi_nn_inference_result_own_tensor_own_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_nn_inference_method_graph_execution_context_get_output((self).__handle, (int32_t) (*name).ptr, (int32_t) (*name).len, ptr);
  wasi_nn_inference_result_own_tensor_own_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_nn_inference_own_tensor_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (wasi_nn_inference_own_error_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
  }
  *ret = result;
}

void wasi_nn_graph_method_graph_init_execution_context(wasi_nn_graph_borrow_graph_t self, wasi_nn_graph_result_own_graph_execution_context_own_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_nn_graph_method_graph_init_execution_context((self).__handle, ptr);
  wasi_nn_graph_result_own_graph_execution_context_own_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_nn_graph_own_graph_execution_context_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (wasi_nn_graph_own_error_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
  }
  *ret = result;
}

void wasi_nn_graph_load(ml_list_graph_builder_t *builder, wasi_nn_graph_graph_encoding_t encoding, wasi_nn_graph_execution_target_t target, wasi_nn_graph_result_own_graph_own_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_nn_graph_load((int32_t) (*builder).ptr, (int32_t) (*builder).len, (int32_t) encoding, (int32_t) target, ptr);
  wasi_nn_graph_result_own_graph_own_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_nn_graph_own_graph_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (wasi_nn_graph_own_error_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
  }
  *ret = result;
}

void wasi_nn_graph_load_by_name(ml_string_t *name, wasi_nn_graph_result_own_graph_own_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_nn_graph_load_by_name((int32_t) (*name).ptr, (int32_t) (*name).len, ptr);
  wasi_nn_graph_result_own_graph_own_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (wasi_nn_graph_own_graph_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (wasi_nn_graph_own_error_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
  }
  *ret = result;
}

extern void __component_type_object_force_link_ml(void);
void __component_type_object_force_link_ml_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_ml();
}
